name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      DATABASE_URL: postgresql+asyncpg://test_user:test_pass@localhost:5432/test_db
      REDIS_URL: redis://localhost:6379
      POSTGRES_HOST: localhost
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
      REDIS_HOST: localhost

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show backend layout
        run: |
          pwd
          ls -la
          ls -la backend
          ls -la backend/app

      - name: Set up Python, install dependencies, and run tests
        working-directory: ./backend
        env:
         PYTHONPATH: ${{ github.workspace }}/backend 
         DB_POSTGRES_HOST: localhost
         DB_POSTGRES_USER: test_user
         DB_POSTGRES_PASSWORD: test_pass
         DB_POSTGRES_DB: test_db
         DB_REDIS_HOST: localhost
         AUTH_JWT_SECRET_KEY: testsecret

        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r ../requirements.txt
          pytest app/tests
